config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :show, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :image, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :make_cocktail, only: [:show, :edit]

  def index
    @query = params[:query]
    @cocktails = if @query
                   Cocktail.where('LOWER(name) like ?', "%#{@query.downcase}%")
                 else
                   Cocktail.all.where.not(image: nil)
                 end
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def update
    @cocktails = Cocktail.find(params[:id])
    @cocktails.update(cocktail_params)
    redirect_to cocktails_path(@cocktails)
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end
  private

  def make_cocktail
    @cocktail = Cocktail.find(params[:id])
    @doses = @cocktail.doses
    @dose = Dose.new
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :doses, :image)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private
  def dose_params
    dose_params = params.require(:dose).permit(:description, :ingredient_id)
    dose_params[:ingredient] = Ingredient.find(dose_params[:ingredient_id])
    dose_params
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-input">
    <%= f.input :name, placeholder: "Old fashioned" %>
    <%= f.input :image %>
    <%= f.input :image_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.submit "Submit", class: "btn" %>
    <%= link_to 'Cancel', cocktails_path, class: "btn-cancel" %>
  </div>
<% end %>

app/views/cocktails/edit.html.erb
 <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1509669803555-fd5edd8d5a41?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60);">
  <div class="form-page pt-3">
    <div class="container new-form">
      <h1>Edit Cocktail</h1>

      <%= simple_form_for([@cocktail, @dose]) do |f| %>

        <div class="form-inputs">
          <%= render 'form' %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1534603649594-2078fe2ad26c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60);">

  <div class="container">
    <h1>Dizzy Lizzy's Cocktail Bar</h1>
    <div id="add">
      <%= link_to "Add Cocktail", new_cocktail_path, class: "btn" %>
    </div>
  </div>

</div>


<div class="container">
  <h2>Dizzy Lizzy Cocktail List</h2>
  <div class="cards" >
    <% @cocktails.each do |cocktail| %>
      <div class="card-category">
        <%= cl_image_tag cocktail.image, height: 300, width: 400, crop: :fill %>
        <%= link_to cocktail.name, cocktail_path(cocktail), class: "card-link" %>
        <%= link_to "Delete", cocktail_path(cocktail.id) , class: "btn-delete", method: :delete, data: { confirm: "DELETE! Are you sure?"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1444728399417-08d2aa39e6f4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60);">

  <div class="container new-form">
    <h1>New Cocktail</h1>
      <%= render 'form' %>
  </div>

</div>

app/views/cocktails/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-12 col-md-6">
      <h1>
        <%= @cocktail.name.capitalize %>
      </h1>
    </div>

    <div class="container container-show">
        <p><%= cl_image_tag @cocktail.image, height: 300, width: 400, crop: :fill %></p>

        <div class="py-3 px-5">
          <div class="p-3 border-bottom">
            <h2>Description</h2>

            <p>This one’s for the cocktail drinkers. The out-there thinkers. Rule breakers. Risk-takers. Memory makers. For the ones who are strong. Be loud. Be wrong. Be game. Be brave. Be bold. For the classy. And the blessed. For the sassy. And the rest. Be badass. Be true. When temptation gets too much. Your secret’s safe with us. Be naughty. Be nice. Don’t think twice. For the gin sippin’, hair flippin’. B*tches be trippin’. For when it’s that kinda night. And when it’s not. You can have it all. It’s your call.</p>
          </div>

          <h2>Ingredient list:</h2>
          <ul>
            <%  @cocktail.doses.each do |dose| %>
            <div class= "d-flex justify-content-between">
              <li><%= dose.ingredient.name %>: <%= dose.description %> </li>
              <%= link_to "Delete", dose_path(dose.id) , class: "btn-delete", method: :delete, data: { confirm: "DELETE! Are you sure?"} %>
            </div>

          <% end %>
          </ul>
        </div>
      </div>

    <div class="links d-flex justify-content-start">
      <%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), class: "btn" %>
      <%= link_to "Cancel",root_path, class: "btn-cancel"  %>
      <%= link_to "Edit", edit_cocktail_path(@cocktail), class: "btn-main"  %>
    </div>
  </div>

</div>

app/views/doses/_form.html.erb
<%= simple_form_for ([@cocktail, @dose]) do |f| %>

  <div class="form-input">
    <%= f.association :ingredient %>
    <%= f.input :description, placeholder: "easy to drink" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn" %>
    <%= link_to 'Cancel', cocktail_path(@cocktail), class: "btn btn-cancel" %>
  </div>
<% end %>

app/views/doses/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1470137237906-d8a4f71e1966?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60);">

  <div class="container new-form">
  <h1>New Dose!</h1>
      <%= render 'form' %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar navbar-expand-lg navbar-expand-md navbar-light navbar-lewagon">
      <%= link_to "/", class: "navbar-brand" do %><i class="fas fa-cocktail"></i>
      <% end %>
      <div>
        <form class="form-inline">
        <input class="form-control mr-sm-2" type="text" name="query" id="search" placeholder="Search cocktails" aria-label="Search">
        <input class="btn" type="submit" value="search">
        </form>
      </div>
    </div>

      <%= yield %>
      <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
      <%= javascript_pack_tag "application" %>
      <footer>
      <div class="footer-container">
        <nav>
          <ul>
            <li><%= link_to "Contact Us", "#" %></li>
            <li><%= link_to "Terms of Use", "#" %></li>
            <li><%= link_to "Privacy Policy", "#" %></li>
            <li><a href="https:selchuk-karakus.dev">© 2019 Copyright: Selchuk-karakus.dev</a></li>
          </ul>
        </nav>
      </div>
      </footer>
    </body>
</html>